### ISSUE TITLE
Invalid pattern causes exception

### ISSUE THREAD

**Issue by jayvdb** [jaimebuelta/ffind#12]
Using glob syntax like `ffind '*.py'` causes `sre_constants.error: nothing to repeat`

```python
$ ffind '*.py'
Traceback (most recent call last):
  File "/usr/bin/ffind", line 6, in <module>
    ffind.run()
  File "/usr/lib/python3.4/site-packages/ffind/ffind.py", line 296, in run
    parse_params_and_search()
  File "/usr/lib/python3.4/site-packages/ffind/ffind.py", line 291, in parse_params_and_search
    return_results=False)
  File "/usr/lib/python3.4/site-packages/ffind/ffind.py", line 131, in search
    compare = create_comparison(file_pattern, ignore_case, fuzzy)
  File "/usr/lib/python3.4/site-packages/ffind/ffind.py", line 59, in create_comparison
    pattern = re.compile(file_pattern, re.IGNORECASE)
  File "/usr/lib64/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.4/sre_parse.py", line 748, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib64/python3.4/sre_parse.py", line 358, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib64/python3.4/sre_parse.py", line 567, in _parse
    raise error("nothing to repeat")
sre_constants.error: nothing to repeat
```

The correct syntax is `ffind '.*\.py$'`.
It would be nice to catch the exception and report a nice error, but it might also be worth detecting a pattern starting with `*` and report a dedicated error that globs are not supported.

**Comment by jaimebuelta** [comment]
(find '\.py$' will work as well, as it's not required to appear at the start of the line)

I've added better reporting, indicating clearly the error and making a suggestion 
https://github.com/jaimebuelta/ffind/commit/6b0faa5f14b1ee65d00b0153b474e1ca0d70f766

**Comment by jayvdb** [comment]
nice!
